include_guard(GLOBAL)

if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(_polycpp_packaging_default ON)
else()
  set(_polycpp_packaging_default OFF)
endif()

option(POLYCPP_ENABLE_PACKAGING "Enable Linux CPack DEB/RPM packaging" ${_polycpp_packaging_default})

if(POLYCPP_ENABLE_PACKAGING AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
  set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
  set(CPACK_PACKAGE_VENDOR "Vladislav Antonov")
  set(CPACK_PACKAGE_CONTACT "Vladislav Antonov <noreply@github.com>")
  set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "polycpp-template: reusable C++ subproject template")
  set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")
  set(CPACK_GENERATOR "DEB;RPM")
  set(CPACK_DEB_COMPONENT_INSTALL ON)
  set(CPACK_RPM_COMPONENT_INSTALL ON)
  set(CPACK_COMPONENTS_GROUPING IGNORE)
  set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
  set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${CPACK_PACKAGE_CONTACT}")
  set(CPACK_RPM_PACKAGE_LICENSE "MIT")
  set(CPACK_RPM_PACKAGE_AUTOREQ ON)

  # Per-component metadata (safe: components need not exist at include time)
  set(CPACK_COMPONENTS_ALL hello_lib_runtime hello_lib_dev hello_app_runtime)

  set(CPACK_COMPONENT_HELLO_LIB_RUNTIME_DISPLAY_NAME "hello-lib runtime")
  set(CPACK_COMPONENT_HELLO_LIB_RUNTIME_DESCRIPTION "Runtime files for the hello_lib STATIC library.")
  set(CPACK_COMPONENT_HELLO_LIB_DEV_DISPLAY_NAME "hello-lib development")
  set(CPACK_COMPONENT_HELLO_LIB_DEV_DESCRIPTION "Public headers and CMake package files for hello_lib.")
  set(CPACK_COMPONENT_HELLO_LIB_DEV_DEPENDS hello_lib_runtime)
  set(CPACK_COMPONENT_HELLO_APP_RUNTIME_DISPLAY_NAME "hello-app runtime")
  set(CPACK_COMPONENT_HELLO_APP_RUNTIME_DESCRIPTION "hello-app executable (depends on hello-lib runtime).")
  set(CPACK_COMPONENT_HELLO_APP_RUNTIME_DEPENDS hello_lib_runtime)

  # DEB per-component names (normalized: lower-case, hyphenated)
  set(CPACK_DEBIAN_HELLO_LIB_RUNTIME_PACKAGE_NAME "polycpp-hello-lib")
  set(CPACK_DEBIAN_HELLO_LIB_DEV_PACKAGE_NAME "polycpp-hello-lib-dev")
  set(CPACK_DEBIAN_HELLO_APP_RUNTIME_PACKAGE_NAME "polycpp-hello-app")
  set(CPACK_DEBIAN_HELLO_LIB_RUNTIME_PACKAGE_SECTION "libs")
  set(CPACK_DEBIAN_HELLO_LIB_DEV_PACKAGE_SECTION "libdevel")
  set(CPACK_DEBIAN_HELLO_APP_RUNTIME_PACKAGE_SECTION "utils")

  # RPM per-component names
  set(CPACK_RPM_HELLO_LIB_RUNTIME_PACKAGE_NAME "polycpp-hello-lib")
  set(CPACK_RPM_HELLO_LIB_DEV_PACKAGE_NAME "polycpp-hello-lib-devel")
  set(CPACK_RPM_HELLO_APP_RUNTIME_PACKAGE_NAME "polycpp-hello-app")
  set(CPACK_RPM_HELLO_LIB_RUNTIME_PACKAGE_GROUP "Development/Libraries")
  set(CPACK_RPM_HELLO_LIB_DEV_PACKAGE_GROUP "Development/Libraries")
  set(CPACK_RPM_HELLO_APP_RUNTIME_PACKAGE_GROUP "Applications/System")

  include(CPack)
else()
  message(STATUS "polycpp: CPack packaging disabled on this platform")
endif()