include_guard(GLOBAL)

if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(_polycpp_packaging_default ON)
else()
  set(_polycpp_packaging_default OFF)
endif()

option(POLYCPP_ENABLE_PACKAGING "Enable Linux CPack DEB/RPM packaging" ${_polycpp_packaging_default})

if(POLYCPP_ENABLE_PACKAGING AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
  set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
  set(CPACK_PACKAGE_VENDOR "Vladislav Antonov")
  set(CPACK_PACKAGE_CONTACT "Vladislav Antonov <noreply@github.com>")
  set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "polycpp-template: reusable C++ subproject template")
  set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")
  set(CPACK_GENERATOR "DEB;RPM")
  set(CPACK_DEB_COMPONENT_INSTALL ON)
  set(CPACK_RPM_COMPONENT_INSTALL ON)
  set(CPACK_COMPONENTS_GROUPING IGNORE)
  set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
  set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${CPACK_PACKAGE_CONTACT}")
  set(CPACK_RPM_PACKAGE_LICENSE "MIT")
  set(CPACK_RPM_PACKAGE_AUTOREQ ON)
  include(CPack)
else()
  message(STATUS "polycpp: CPack packaging disabled on this platform")
endif()